bg = #1f2329;
bg1 = #282c34;
bg2 = #30363f;
bg3 = #323641;

fg = #a0a8b7;


dark_cyan = #266269;
dark_purple = #7e3992;
dark_red = #8b3434;
dark_yellow = #835d1a;

blue = #4fa6ed;
cyan = #48b0bd;
yellow = #e2b86b;
orange = #cc9057;
purple = #bf68d9;
green = #8ebd6b;
red = #e55561;

grey = #535965;
light_grey = #7a818e;
black = #0e1013;
